### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by varoudis** [jakebian/quiver#13] opened 2016-11-16 10:23 UTC
http displays everything fine. both the model and the images.
I have used both relative and absolute path from root in order to point to the test pngs but I get the same error.
Ideas?

```
10.200.200.14 - - [2016-11-16 10:17:23] "GET / HTTP/1.1" 304 181 0.003791
10.200.200.14 - - [2016-11-16 10:17:23] "GET /app.c1d3d21cfba8c1aabed6806773c8f0ba.css HTTP/1.1" 304 182 0.002744
10.200.200.14 - - [2016-11-16 10:17:23] "GET /app.14b8092d6ea379715007.js HTTP/1.1" 304 185 0.002481
10.200.200.14 - - [2016-11-16 10:17:23] "GET /vendor.280c5ce1d78077ee8d66.js HTTP/1.1" 304 183 0.001901
10.200.200.14 - - [2016-11-16 10:17:24] "GET /inputs HTTP/1.1" 200 2317 0.001542
10.200.200.14 - - [2016-11-16 10:17:24] "GET /model HTTP/1.1" 200 51636 0.022055
[2016-11-16 10:17:28,776] ERROR in app: Exception on /layer/convolution2d_2/sub_100_00198524.png [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/server.py", line 74, in get_layer_outputs
    input_img = load_img(input_path, single_input_shape)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/util.py", line 25, in load_img
    img = image.load_img(input_path, target_size=target_shape)
  File "/opt/conda/lib/python2.7/site-packages/keras/preprocessing/image.py", line 173, in load_img
    img = Image.open(path)
  File "/opt/conda/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'sub_100_00198524.png'
10.200.200.14 - - [2016-11-16 10:17:28] "GET /layer/convolution2d_2/sub_100_00198524.png HTTP/1.1" 500 412 0.003709
[2016-11-16 10:17:28,781] ERROR in app: Exception on /predict/sub_100_00198524.png [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/server.py", line 98, in get_prediction
    input_img = load_img(input_path, single_input_shape)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/util.py", line 25, in load_img
    img = image.load_img(input_path, target_size=target_shape)
  File "/opt/conda/lib/python2.7/site-packages/keras/preprocessing/image.py", line 173, in load_img
    img = Image.open(path)
  File "/opt/conda/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'sub_100_00198524.png'
10.200.200.14 - - [2016-11-16 10:17:28] "GET /predict/sub_100_00198524.png HTTP/1.1" 500 412 0.003878
```

**Comment by varoudis** [comment] 2016-11-16 10:49
a hack to make it work is to move the .py file in the dir that holds the test images.

**Comment by kretes** [comment] 2016-11-16 12:12
Yes, I think this is a duplicate of https://github.com/jakebian/quiver/issues/9

**Comment by varoudis** [comment] 2016-11-16 12:15
right!

**Comment by jakebian** [comment] 2016-11-16 16:37
Closing as duplicate

**Closed by jakebian** 2016-11-16 16:37 UTC
