### ISSUE TITLE
Work with Theano

### ISSUE THREAD

**Issue by isaacgerg** [jakebian/quiver#6] opened 2016-11-15 20:26 UTC
Get this working with Theano.  Moreso, get it working with the keras genetic backend so that it works smoothly with both th and tf.

**Comment by jakebian** [comment] 2016-11-15 20:27
Duplicate of https://github.com/jakebian/quiver/issues/1

**Closed by jakebian** 2016-11-15 20:28 UTC

**Comment by 945226956** [comment] 2019-05-30 07:39
hello https://github.com/jakebian/quiver/issues/1 is missing
