### ISSUE TITLE
quiver requires model to have one-hot output of 1000 classes

### ISSUE THREAD

**Issue by isaacgerg** [jakebian/quiver#18] opened 2016-11-17 19:07 UTC
imagenet_utils.py contains decode_predictions() which is hardcoded for 1000 classes and one-hot output.  Should support arbitrary model output.  Recommend test on mnist dataset for verification.

**Comment by jakebian** [comment] 2016-11-17 19:10
Duplicate of https://github.com/jakebian/quiver/issues/12 0 - see the comment there and [this task](https://github.com/jakebian/quiver/projects/1#card-818905), the decoding is only meant to work for imagenet atm.

Right now iff the model fails to be that the prediction endpoint will fail, but the other parts of the dashboard should function correctly.

**Closed by jakebian** 2016-11-17 19:10 UTC
