### ISSUE TITLE
fails with 404 not found

### ISSUE THREAD

**Issue by mc0514** [jakebian/quiver#17] opened 2016-11-17 07:08 UTC
When I add the quiver in my code 
`server.launch(
        model, # a Keras Model

        # where to store temporary files generatedby quiver (e.g. image files of layers)
        temp_folder='tmp/',

        # a folder where input images are stored
        input_folder='dataset/',

        # the localhost port the dashboard is to be served on
        port=9000
    )`
and run it, but the browser shows 
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
the terminal shows 

127.0.0.1 - - [2016-11-17 15:02:26] "GET / HTTP/1.1" 404 374 0.006884
Created new window in existing browser session.
127.0.0.1 - - [2016-11-17 15:02:26] "GET /favicon.ico HTTP/1.1" 404 374 0.000999
127.0.0.1 - - [2016-11-17 15:03:00] "GET / HTTP/1.1" 404 374 0.000542
127.0.0.1 - - [2016-11-17 15:03:01] "GET / HTTP/1.1" 404 374 0.000735

**Comment by isaacgerg** [comment] 2016-11-17 09:43
Are you installing with pip or development version?  Try port 3000.

**Comment by mc0514** [comment] 2016-11-17 10:00
@isaacgerg I installed it with pip. I tried port 3000 and not worked. Had you solved this problem?

**Comment by varoudis** [comment] 2016-11-17 10:57
installing the current git from pip git+https gives me a 404. Installing via the typical pip version works.

**Comment by isaacgerg** [comment] 2016-11-17 14:17
Try this: `npm run deploy:prod`

**Comment by jakebian** [comment] 2016-11-17 18:18
I'll start [including the dist folder in git](https://github.com/jakebian/quiver/projects/1#card-833444) so that people no longer need to run deploy (convenience at the cost of messier commit messages).

This is a duplicate of https://github.com/jakebian/quiver/issues/2, if you're still having trouble we should have this discussion on [gitter](https://gitter.im/quiverEngine/Lobby)

**Closed by jakebian** 2016-11-17 18:18 UTC
